name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.10.14
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: .cache/pip
          key: pip-${{ hashFiles('poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            pip-
      
      - name: Cache poetry packages
        uses: actions/cache@v4
        with:
          path: .cache/poetry
          key: poetry-${{ hashFiles('poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            poetry-
      
      - name: Install Poetry
        run: pip install poetry==1.8.3
      
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config cache-dir .cache/poetry
          poetry config --list
      
      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      
      - name: Install dependencies with lint extras
        run: poetry install --with lint
      
      - name: Run ruff linting
        run: poetry run ruff check

  test:
    runs-on: ubuntu-latest
    container: python:3.10.14
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: .cache/pip
          key: pip-${{ hashFiles('poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            pip-
      
      - name: Cache poetry packages
        uses: actions/cache@v4
        with:
          path: .cache/poetry
          key: poetry-${{ hashFiles('poetry.lock', '.github/workflows/ci.yml') }}
          restore-keys: |
            poetry-
      
      - name: Install Poetry
        run: pip install poetry==1.8.3
      
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config cache-dir .cache/poetry
          poetry config --list
      
      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes
      
      - name: Install dependencies with test extras
        run: poetry install --with test
      
      - name: Run pytest
        run: poetry run pytest
